import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { poppins } from "@/lib/font";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";
import MobileNavbar from "@/components/MobileNavbar";
import Footer from "@/components/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <section className="fixed left-0 top-5 w-full z-[999]">
            <Navbar/>
            <MobileNavbar/>
          </section>
          <main className="">{children}</main>
          <section>
            <Footer/>
          </section>
        </ThemeProvider>
      </body>
    </html>
  );
}
